
image: gitpod/workspace-full-vnc
tasks:
  - init: yarn install
    command: yarn run dev
vscode:
  extensions:
    - csstools.postcss
    - svelte.svelte-vscode
    - esbenp.prettier-vscode
    - bradlc.vscode-tailwindcss
