name: Yarn Check And Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'yarn'

            - name: Install Dependencies
              run: yarn

            - name: Run Typescript Checks
              run: yarn check

            - name: Test Build
              run: yarn build
